spring:
  devtools:
    restart:
      enabled: true  #设置开启热部署
  freemarker:
    template-loader-path: classpath:/templates
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: false
    expose-session-attributes: false
    request-context-attribute: request
    suffix: .ftl
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  resources: classpath:static/
  mvc:
    static-path-pattern: /static/**

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 200MB
server:
  port: 8080
  servlet:
    context-path: /mvc
    session:
      cookie:
        path: /
  tomcat:
    uri-encoding: UTF-8
    maxThreads: 1000
    minSpareThreads: 100
    acceptCount: 500
logPath: /home/logs/tomcatlogs/mvc